*-----------------------------------------------------------
* Title      :  PRACTICAL_03
* Written by :  Oleksandr Storozhuk
* Date       :  26/01/2026
* Description:  PART 2
*-----------------------------------------------------------
    ORG    $1000
START:                  ; first instruction of program

* Put program code here
    
    LEA     $4000,  A2
    MOVE.B  #100,   (A2)
    SUB.B   #10,    (A2)
     

    SIMHALT             ; halt simulator

* Put variables and constants here

    END    START        ; last line of source

*~Font name~Courier New~
*~Font size~10~
*~Tab type~1~
*~Tab size~4~
